export const dataForTemplateGeneration = [
  {
    id: 1,
    title: "Trend 1",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 2,
    title: "Trend 2",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 3,
    title: "Trend 3",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 4,
    title: "Trend 4",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 5,
    title: "Trend 5",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 6,
    title: "Trend 6",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 7,
    title: "Trend 7",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 8,
    title: "Trend 8",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 9,
    title: "Trend 9",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
  {
    id: 10,
    title: "Trend 10",
    description: `As of early 2025, ladies' kurtas are embracing a blend of traditional elegance and contemporary flair. Here are some of the latest trends:\n\n1. A-Line Kurtas: Featuring a flared silhouette that resembles the letter \"A,\" these kurtas offer a flattering fit suitable for various body types. They are versatile, comfortable, and can be paired with leggings, palazzos, or even jeans for a chic look.\n\n2. Anarkali Kurtas: Drawing inspiration from Mughal fashion, Anarkali kurtas are characterized by their long, flowing design and intricate embroidery. They exude a royal appeal, making them ideal for weddings, festivals, and other grand occasions.\n\n3. Cape Style Kurtas: Merging traditional attire with modern design elements, cape-style kurtas feature an attached or detachable cape, adding a layer of sophistication and drama to the ensemble.\n\n4. Peplum Kurtas: These kurtas incorporate a peplum—a short, flared, gathered, or pleated strip of fabric attached at the waist—offering a contemporary twist to traditional wear. They are perfect for those looking to add a playful yet elegant touch to their outfit.`,
    images: [
      "https://d1til5nimponbk.cloudfront.net/templates/1.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/2.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/3.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
      "https://d1til5nimponbk.cloudfront.net/templates/4.jpg",
    ],
  },
];
