// interface Template {
//   id: number;
//   title: string;
//   description: string;
//   images: string[];
// }
export const createTemplate = (templateData) => {
  let pages = [];
  let id = 1;

  const firstPage = createFirstPage(
    id++,
    templateData.title,
    templateData.image
  );
  pages.push(firstPage);

  templateData.trends.map((trend, index) => {
    const trendsFirstPage = createTrendsFirstPage(
      id++,
      trend.page1Data.title,
      trend.page1Data.description,
      trend.page1Data.image,
      trend.page1Data.number
    );

    const trendsSecondPage = createTrendsSecondPage(
      id++,
      trend.page2Data.title,
      trend.page2Data.description,
      trend.page2Data.designers,
      trend.page2Data.mainImage,
      trend.page2Data.images
    );

    const trendsThirdPage = createTrendsThirdPage(
      id++,
      trend.page3Data.title,
      trend.page3Data.image1,
      trend.page3Data.type1,
      trend.page3Data.percent1,
      trend.page3Data.desc1,
      trend.page3Data.image2,
      trend.page3Data.type2,
      trend.page3Data.percent2,
      trend.page3Data.desc2
    );

    pages.push(trendsFirstPage);
    pages.push(trendsSecondPage);
    pages.push(trendsThirdPage);
  });

  return { pages };
};

const createFirstPage = (id, description, image) => {
  return {
    id: id,
    canvasData: {
      version: "6.5.2",
      objects: [
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 399.0625,
          top: 405.1651,
          width: 736,
          height: 919,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.0926,
          scaleY: 0.9924,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          src: image,
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          fontSize: 43,
          fontWeight: "bold",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1.2,
          text: "ICH",
          charSpacing: 250,
          textAlign: "center",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 27,
          top: 150,
          width: 96.5532,
          height: 48.59,
          fill: "#f3f1f1",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: null,
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 45,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1.2,
          text: description,
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 30,
          top: 291,
          width: 592.1249,
          height: 172.89,
          fill: "#f3f1f1",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: null,
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
      background: "white",
    },
    width: 800,
    height: 500,
  };
};

const createTrendsFirstPage = (id, title, description, image, number) => {
  return {
    id: id,
    canvasData: {
      version: "6.5.2",
      objects: [
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 401.5825,
          top: 235.7757,
          width: 880,
          height: 586,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.9193,
          scaleY: 0.9193,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          src: image,
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          fontSize: 150,
          fontWeight: "bold",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1.2,
          text: number,
          charSpacing: -100,
          textAlign: "center",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 630,
          top: 67,
          width: 84.4229,
          height: 169.5,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: null,
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 50,
          fontWeight: "bold",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1.2,
          text: title,
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 9,
          top: 369,
          width: 234.252,
          height: 124.3,
          fill: "#f3f1f1",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: null,
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 17,
          fontWeight: "bold",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1.2,
          text: description,
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 261.1249,
          top: 422,
          width: 484.6533,
          height: 65.314,
          fill: "#ffffff",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: null,
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
      background: "white",
    },
    width: 800,
    height: 500,
  };
};

const createTrendsSecondPage = (
  id,
  title,
  description,
  numberedText,
  largeImage,
  smallImages
) => {
  return {
    id: id,
    canvasData: {
      version: "6.5.2",
      objects: [
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 727.9849,
          top: 86.3409,
          width: 474,
          height: 474,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.3376,
          scaleY: 0.377,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          src: smallImages[0],
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 710.2808,
          top: 325.023,
          width: 474,
          height: 474,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.3321,
          scaleY: 0.3321,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          clipPath: {
            radius: 237,
            startAngle: 0,
            endAngle: 360,
            counterClockwise: false,
            inverted: false,
            absolutePositioned: false,
            type: "Circle",
            version: "6.5.2",
            originX: "center",
            originY: "center",
            left: 0,
            top: 0,
            width: 474,
            height: 474,
            fill: "rgb(0,0,0)",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
          },
          src: smallImages[1],
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 555.5402,
          top: 160.8944,
          width: 474,
          height: 474,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.3395,
          scaleY: 0.4173,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          clipPath: {
            rx: 47.4,
            ry: 47.4,
            inverted: false,
            absolutePositioned: false,
            type: "Rect",
            version: "6.5.2",
            originX: "center",
            originY: "center",
            left: 0,
            top: 0,
            width: 474,
            height: 474,
            fill: "rgb(0,0,0)",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
          },
          src: smallImages[2],
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 547.9157,
          top: 368.3654,
          width: 474,
          height: 474,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.28,
          scaleY: 0.28,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          clipPath: {
            rx: 47.4,
            ry: 47.4,
            inverted: false,
            absolutePositioned: false,
            type: "Rect",
            version: "6.5.2",
            originX: "center",
            originY: "center",
            left: 0,
            top: 0,
            width: 474,
            height: 474,
            fill: "rgb(0,0,0)",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
          },
          src: smallImages[3],
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 350.3541,
          top: 250.4583,
          width: 2000,
          height: 2690,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.1174,
          scaleY: 0.1836,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          clipPath: {
            rx: 200,
            ry: 200,
            inverted: false,
            absolutePositioned: false,
            type: "Rect",
            version: "6.5.2",
            originX: "center",
            originY: "center",
            left: 0,
            top: 0,
            width: 2000,
            height: 2690,
            fill: "rgb(0,0,0)",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
          },
          src: largeImage,
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          fontSize: 31,
          fontWeight: "bold",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1.2,
          text: title,
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 30,
          top: 10,
          width: 192.7083,
          height: 119.102,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 13,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1.2,
          text: description,
          charSpacing: 0,
          textAlign: "left",
          styles: [
            {
              start: 273,
              end: 372,
              style: {
                fontSize: 13,
                fontWeight: "normal",
                fontFamily: "Arial",
                fontStyle: "normal",
                underline: false,
                overline: false,
                linethrough: false,
                stroke: null,
                strokeWidth: 1,
                fill: "#000000",
                deltaY: 0,
                textBackgroundColor: "",
              },
            },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 35,
          top: 143,
          width: 181.7083,
          height: 261.482,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 11,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1.2,
          text: numberedText,
          charSpacing: 0,
          textAlign: "left",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 38,
          top: 417,
          width: 163.7083,
          height: 72.094,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
      background: "white",
    },
    width: 800,
    height: 500,
  };
};

const createTrendsThirdPage = (
  id,
  title,
  image1,
  type1,
  percent1,
  desc1,
  image2,
  type2,
  percent2,
  desc2
) => {
  return {
    id: id,
    canvasData: {
      version: "6.5.2",
      objects: [
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 447.3682,
          top: 266.016,
          width: 474,
          height: 474,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.331,
          scaleY: 0.363,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          clipPath: {
            radius: 237,
            startAngle: 0,
            endAngle: 360,
            counterClockwise: false,
            inverted: false,
            absolutePositioned: false,
            type: "Circle",
            version: "6.5.2",
            originX: "center",
            originY: "center",
            left: 0,
            top: 0,
            width: 474,
            height: 474,
            fill: "rgb(0,0,0)",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
          },
          src: image2,
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          fontSize: 39,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 2.1,
          text: type1,
          charSpacing: 0,
          textAlign: "center",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 206.6367,
          top: 45.8773,
          width: 87.7217,
          height: 44.07,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.8769,
          scaleY: 1.002,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 61,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: "2.1",
          text: percent1,
          charSpacing: -200,
          textAlign: "center",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 221.5436,
          top: 107.0012,
          width: 99.3871,
          height: 68.93,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.8769,
          scaleY: 1.002,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          type: "Line",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 311.9713,
          top: 104.0012,
          width: 0,
          height: 400,
          fill: "rgb(0,0,0)",
          stroke: "black",
          strokeWidth: 2,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.5607,
          scaleY: 0.1511,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          x1: 0,
          x2: 0,
          y1: -200,
          y2: 200,
        },
        {
          fontSize: 11,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1,
          text: desc1,
          charSpacing: 0,
          textAlign: "left",
          styles: [
            { start: 26, end: 35, style: { fontWeight: "bold" } },
            { start: 43, end: 55, style: { fontWeight: "bold" } },
            { start: 79, end: 96, style: { fontWeight: "bold" } },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 322.3843,
          top: 102.9951,
          width: 163.6797,
          height: 62.15,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 30,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 2.1,
          text: type2,
          charSpacing: 0,
          textAlign: "center",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 525.9425,
          top: 200,
          width: 87.7217,
          height: 33.9,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          fontSize: 46,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: "2.1",
          text: percent2,
          charSpacing: -100,
          textAlign: "center",
          styles: [],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 530.5909,
          top: 264,
          width: 99.3871,
          height: 51.98,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          type: "Line",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 615.3184,
          top: 261,
          width: 0,
          height: 400,
          fill: "rgb(0,0,0)",
          stroke: "black",
          strokeWidth: 2,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.3242,
          scaleY: 0.1507,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          x1: 0,
          x2: 0,
          y1: -200,
          y2: 200,
        },
        {
          fontSize: 12,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: 1,
          text: desc2,
          charSpacing: 0,
          textAlign: "left",
          styles: [
            { start: 26, end: 35, style: { fontWeight: "bold" } },
            { start: 42, end: 54, style: { fontWeight: "bold" } },
            { start: 78, end: 96, style: { fontWeight: "bold" } },
          ],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 623.1538,
          top: 256,
          width: 163.7593,
          height: 67.8,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "#ffffff",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
        {
          cropX: 0,
          cropY: 0,
          type: "Image",
          version: "6.5.2",
          originX: "center",
          originY: "center",
          left: 105.9849,
          top: 102.3409,
          width: 474,
          height: 474,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.3376,
          scaleY: 0.377,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          clipPath: {
            rx: 47.4,
            ry: 47.4,
            inverted: false,
            absolutePositioned: false,
            type: "Rect",
            version: "6.5.2",
            originX: "center",
            originY: "center",
            left: 0,
            top: 0,
            width: 474,
            height: 474,
            fill: "rgb(0,0,0)",
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: "butt",
            strokeDashOffset: 0,
            strokeLineJoin: "miter",
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: "",
            fillRule: "nonzero",
            paintFirst: "fill",
            globalCompositeOperation: "source-over",
            skewX: 0,
            skewY: 0,
          },
          src: image1,
          crossOrigin: "anonymous",
          filters: [
            { type: "Brightness", brightness: 0 },
            { type: "Contrast", contrast: 0 },
            { type: "Blur", blur: 0 },
          ],
        },
        {
          fontSize: 51,
          fontWeight: "normal",
          fontFamily: "Arial",
          fontStyle: "normal",
          lineHeight: "1",
          text: title,
          charSpacing: 0,
          textAlign: "center",
          styles: [{ start: 21, end: 33, style: { fontWeight: "bold" } }],
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          underline: false,
          overline: false,
          linethrough: false,
          textBackgroundColor: "",
          direction: "ltr",
          minWidth: 20,
          splitByGrapheme: false,
          type: "Textbox",
          version: "6.5.2",
          originX: "left",
          originY: "top",
          left: 15,
          top: 325,
          width: 488.9131,
          height: 115.26,
          fill: "#000000",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: null,
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
        },
      ],
      background: "white",
    },
    width: 800,
    height: 500,
  };
};

// const pages = templatedata.map((data) => {
//   return {
//     id: data.id,
//     canvasData: {
//       version: "6.5.2",
//       objects: [
//         {
//           radius: 50,
//           startAngle: 0,
//           endAngle: 360,
//           counterClockwise: false,
//           type: "Circle",
//           version: "6.5.2",
//           originX: "left",
//           originY: "top",
//           left: -48,
//           top: -42.0001,
//           width: 100,
//           height: 100,
//           fill: "#c7336e",
//           stroke: null,
//           strokeWidth: 1,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 1.6039,
//           scaleY: 1.6039,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 0.5,
//           shadow: {
//             color: "#bd2eaa",
//             blur: 13,
//             offsetX: 0,
//             offsetY: 0,
//             affectStroke: false,
//             nonScaling: false,
//             type: "shadow",
//           },
//           visible: true,
//           backgroundColor: "",
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//         },
//         {
//           radius: 50,
//           startAngle: 0,
//           endAngle: 360,
//           counterClockwise: false,
//           type: "Circle",
//           version: "6.5.2",
//           originX: "left",
//           originY: "top",
//           left: -40,
//           top: 379,
//           width: 100,
//           height: 100,
//           fill: "#c7336e",
//           stroke: null,
//           strokeWidth: 1,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 1.6039,
//           scaleY: 1.6039,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 0.5,
//           shadow: {
//             color: "#bd2eaa",
//             blur: 13,
//             offsetX: 0,
//             offsetY: 0,
//             affectStroke: false,
//             nonScaling: false,
//             type: "shadow",
//           },
//           visible: true,
//           backgroundColor: "",
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//         },
//         {
//           fontSize: 40,
//           fontWeight: "normal",
//           fontFamily: "Aoboshi One",
//           fontStyle: "normal",
//           lineHeight: 1.2,
//           text: data.title,
//           charSpacing: 0,
//           textAlign: "center",
//           styles: [],
//           pathStartOffset: 0,
//           pathSide: "left",
//           pathAlign: "baseline",
//           underline: false,
//           overline: false,
//           linethrough: false,
//           textBackgroundColor: "",
//           direction: "ltr",
//           minWidth: 20,
//           splitByGrapheme: false,
//           type: "Textbox",
//           version: "6.5.2",
//           originX: "left",
//           originY: "top",
//           left: 275,
//           top: 7.9999,
//           width: 200,
//           height: 45.2,
//           fill: "#000000",
//           stroke: null,
//           strokeWidth: 1,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 1,
//           scaleY: 1,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 1,
//           shadow: null,
//           visible: true,
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//         },
//         {
//           radius: 50,
//           startAngle: 0,
//           endAngle: 360,
//           counterClockwise: false,
//           type: "Circle",
//           version: "6.5.2",
//           originX: "left",
//           originY: "top",
//           left: 396.1,
//           top: -41,
//           width: 100,
//           height: 100,
//           fill: "#637097",
//           stroke: null,
//           strokeWidth: 1,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 5.9235,
//           scaleY: 5.7859,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 0.5,
//           shadow: {
//             color: "#857a7a",
//             blur: 24,
//             offsetX: 1,
//             offsetY: -5,
//             affectStroke: false,
//             nonScaling: false,
//             type: "shadow",
//           },
//           visible: true,
//           backgroundColor: "",
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//         },
//         {
//           fontSize: 13,
//           fontWeight: "normal",
//           fontFamily: "Segoe UI",
//           fontStyle: "normal",
//           lineHeight: 1.2,
//           text: data.description,
//           charSpacing: 0,
//           textAlign: "left",
//           styles: [],
//           pathStartOffset: 0,
//           pathSide: "left",
//           pathAlign: "baseline",
//           underline: false,
//           overline: false,
//           linethrough: false,
//           textBackgroundColor: "",
//           direction: "ltr",
//           minWidth: 20,
//           splitByGrapheme: false,
//           type: "Textbox",
//           version: "6.5.2",
//           originX: "left",
//           originY: "top",
//           left: 62,
//           top: 53.8206,
//           width: 385.5581,
//           height: 402.506,
//           fill: "#000000",
//           stroke: null,
//           strokeWidth: 1,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 1,
//           scaleY: 1,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 1,
//           shadow: null,
//           visible: true,
//           backgroundColor: null,
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//         },
//         {
//           cropX: 0,
//           cropY: 0,
//           type: "Image",
//           version: "6.5.2",
//           originX: "center",
//           originY: "center",
//           left: 554.3211,
//           top: 152.17,
//           width: 474,
//           height: 474,
//           fill: "rgb(0,0,0)",
//           stroke: null,
//           strokeWidth: 0,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 0.3389,
//           scaleY: 0.355,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 1,
//           shadow: null,
//           visible: true,
//           backgroundColor: "",
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//           src: data.images[0],
//           crossOrigin: "anonymous",
//           filters: [
//             { type: "Brightness", brightness: 0 },
//             { type: "Contrast", contrast: 0 },
//             { type: "Blur", blur: 0 },
//           ],
//         },
//         {
//           cropX: 0,
//           cropY: 0,
//           type: "Image",
//           version: "6.5.2",
//           originX: "center",
//           originY: "center",
//           left: 718.5492,
//           top: 239.6527,
//           width: 474,
//           height: 474,
//           fill: "rgb(0,0,0)",
//           stroke: null,
//           strokeWidth: 0,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 0.323,
//           scaleY: 0.3192,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 1,
//           shadow: null,
//           visible: true,
//           backgroundColor: "",
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//           src: data.images[1],
//           crossOrigin: "anonymous",
//           filters: [
//             { type: "Brightness", brightness: 0 },
//             { type: "Contrast", contrast: 0 },
//             { type: "Blur", blur: 0 },
//           ],
//         },
//         {
//           cropX: 0,
//           cropY: 0,
//           type: "Image",
//           version: "6.5.2",
//           originX: "center",
//           originY: "center",
//           left: 717.5536,
//           top: 81.2499,
//           width: 474,
//           height: 474,
//           fill: "rgb(0,0,0)",
//           stroke: null,
//           strokeWidth: 0,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 0.3272,
//           scaleY: 0.3167,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 1,
//           shadow: null,
//           visible: true,
//           backgroundColor: "",
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//           src: data.images[2],
//           crossOrigin: "anonymous",
//           filters: [
//             { type: "Brightness", brightness: 0 },
//             { type: "Contrast", contrast: 0 },
//             { type: "Blur", blur: 0 },
//           ],
//         },
//         {
//           cropX: 0,
//           cropY: 0,
//           type: "Image",
//           version: "6.5.2",
//           originX: "center",
//           originY: "center",
//           left: 555.6857,
//           top: 325.1527,
//           width: 474,
//           height: 474,
//           fill: "rgb(0,0,0)",
//           stroke: null,
//           strokeWidth: 0,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 0.3352,
//           scaleY: 0.3424,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 1,
//           shadow: null,
//           visible: true,
//           backgroundColor: "",
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//           src: data.images[3],
//           crossOrigin: "anonymous",
//           filters: [
//             { type: "Brightness", brightness: 0 },
//             { type: "Contrast", contrast: 0 },
//             { type: "Blur", blur: 0 },
//           ],
//         },
//         {
//           cropX: 0,
//           cropY: 0,
//           type: "Image",
//           version: "6.5.2",
//           originX: "center",
//           originY: "center",
//           left: 718.0509,
//           top: 409.7499,
//           width: 474,
//           height: 474,
//           fill: "rgb(0,0,0)",
//           stroke: null,
//           strokeWidth: 0,
//           strokeDashArray: null,
//           strokeLineCap: "butt",
//           strokeDashOffset: 0,
//           strokeLineJoin: "miter",
//           strokeUniform: false,
//           strokeMiterLimit: 4,
//           scaleX: 0.3251,
//           scaleY: 0.3521,
//           angle: 0,
//           flipX: false,
//           flipY: false,
//           opacity: 1,
//           shadow: null,
//           visible: true,
//           backgroundColor: "",
//           fillRule: "nonzero",
//           paintFirst: "fill",
//           globalCompositeOperation: "source-over",
//           skewX: 0,
//           skewY: 0,
//           src: data.images[4],
//           crossOrigin: "anonymous",
//           filters: [
//             { type: "Brightness", brightness: 0 },
//             { type: "Contrast", contrast: 0 },
//             { type: "Blur", blur: 0 },
//           ],
//         },
//       ],
//       background: "white",
//     },
//     width: 800,
//     height: 500,
//   };
// });
